version: "2"
services:

  rabbitmq-1:
    container_name: rabbitmq-1    
    networks: ["vnet"]
    hostname: rabbitmq-1.vnet
    build: .
    ports:  
      - 15672:15672
    command: -server 1 1 vnet


networks: 
  vnet: 
    external: 
      name: vnet 
    